spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dzmil_ecommerce
    username: postgres
    password: 'sweetride'
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

log4j:
  logger:
      org:
        hibernate:
          SQL: DEBUG
          type: TRACE